/*	SCCS Id: @(#)date.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Tue May 17 21:56:16 2022"
#define BUILD_TIME (1652792176L)

#define VERSION_NUMBER 0x03040300UL
#define VERSION_FEATURES 0x181e0c46UL
#define IGNORED_FEATURES 0x00800000UL
#define VERSION_SANITY1 0x261d0184UL
#define VERSION_SANITY2 0xa881a584UL

#define VERSION_STRING "3.4.3"
#define VERSION_ID \
 "Windows NetHack brass tty Ver.yymmdd - last build Tue May 17 21:56:16 2022."

